# Generated by Django 4.0 on 2025-03-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
