# Generated by Django 4.0 on 2025-03-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.RemoveField(
            model_name='module',
            name='created_at',
        ),
    ]
