# Generated by Django 4.0 on 2025-03-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_alter_module_options_remove_module_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='version',
            field=models.CharField(default='1.0.0', max_length=10),
        ),
    ]
