# Generated by Django 4.0 on 2025-03-21 17:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_module_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100, unique=True)),
                ('is_create', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_update', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
    ]
