# Generated by Django 4.0 on 2025-03-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='is_read',
            new_name='is_edit',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='is_update',
        ),
    ]
